### ISSUE TITLE
Error after pressing Knit

### ISSUE THREAD

**Issue by jtruffa** [csgillespie/efficientR#113]
Hi, 

I´ve installed the dependencies, cloned the repo and presss Knit.

But this error message arose:

 Error 5977

Error in parse(text = x) : &lt;text&gt;:4:25: unexpected symbol
3:     person("Romain", "Francois", , "romain@r-enthusiasts.com", "aut"),
4:     person("Kirill", "M"uller
                           ^
Calls: &lt;Anonymous&gt; ... citation -&gt; .read_authors_at_R_field -&gt; eval -&gt; parse
Ejecuci'on interrumpida

Any hints?

**Comment by csgillespie** [comment]
I can't reproduce.  Would you:

 * Make sure you are using the latest version R & RStudio
 * Run `update.packages`

If that doesn't work. Send me the two generated .bib files.

**Comment by jtruffa** [comment]
I think you mean theses to files.

Thanks in advance!

[bibfiles.zip](https://github.com/csgillespie/efficientR/files/378652/bibfiles.zip)

**Comment by csgillespie** [comment]
Could you try creating and building this simple Rmd document:

```
---
title: "Untitled"
author: "Colin Gillespie"
date: "22 July 2016"
output: html_document
bibliography: [refs.bib]
---

```{r setup, include=FALSE}
knitr::write_bib("tibble", file="refs.bib")
```

# test

[@R-tibble]
```

**Comment by jtruffa** [comment]
I named it Test.Rmd
Press the knit HTML and gives me an error that I can´t cut and paste.

So I run from the console: > rmarkdown::render("test.Rmd")

And the output is:


processing file: test.Rmd
  |................................                                 |  50%
  ordinary text without R code

  |.................................................................| 100%
label: setup (with options) 
List of 1
 $ include: logi FALSE

Quitting from lines 11-12 (test.Rmd) 
Error in parse(text = x) : <text>:4:25: unexpected symbol
3:     person("Romain", "Francois", , "romain@r-enthusiasts.com", "aut"),
4:     person("Kirill", "M"uller
                           ^

**Comment by csgillespie** [comment]
@jtruffa I think this might be bug in `write_bib`. See https://github.com/yihui/knitr/issues/1256
