### ISSUE TITLE
The [@Wickham2014] reference doesn't work in bookdown's custom blocks for pdf output

### ISSUE THREAD

**Issue by adamryczkowski** [csgillespie/efficientR#119]
The reference can be found in the beginning of chapter 3.7.1 "Function closures".

It is a manifestation of the bookdown's [issue 117: Treat blocks as markdown](https://github.com/rstudio/bookdown/issues/117). I read that it would be included in the v0.2 of the bookdown, so no fix will be needed. For pdf, a valid LaTeX still can be put, but for some reasons pandoc doesn't use the `cite` package, but use home-grew solution. So the correct walkaround will be tu put:

`(\protect\hyperlink{ref-Wickham2014}{Wickham 2014})`

in place of the `[@Wickham2014]`.

**Comment by Robinlovelace** [comment]
How come this issue was closed? Just out of curiosity.

**Comment by adamryczkowski** [comment]
There is nothing to fix ATM, so I decided there is no point in keeping it opened.
