### ISSUE TITLE
Perhaps let people know how long it takes to run the examples

### ISSUE THREAD

**Issue by njtierney** [csgillespie/efficientR#126]
Thanks for writing this book! Enjoying it so far!

In the example [here in chapter two](https://csgillespie.github.io/efficientR/set-up.html#operating-system-and-resource-monitoring), it says to run these exercises:

```r
# 1: Create large dataset
X = matrix(rnorm(1e8), nrow = 1e7)
# 2: Find the median of each column using a single core
r1 = lapply(X, median)
# 3: Find the median of each column using many cores
r2 = parallel::mclapply(X, median) # runs in serial on Windows
```

However, I stopped running mine after 20 minutes, because I was still running on r1.

Maybe people have more than 16Gb of ram, and maybe there's something up with my computer, but perhaps it might be a better example doesn't take so long to run, or you mention to the users of the book "hey, this takes a while to run, expect around xx minutes".

Again, thanks for writing this book!

**Comment by csgillespie** [comment]
Thanks for the comment it's come just in time for the last round of revisions. I agree that  20 minutes does seem a little steep!

**Comment by njtierney** [comment]
No worries, looking forward to reading the rest of it! Thank you for your hard work, and for making it available for free online! :)
