### ISSUE TITLE
No benchmarks of ifelse

### ISSUE THREAD

**Issue by Robinlovelace** [csgillespie/efficientR#130]
It is said that ifelse is not fast, but we've not benchmarked it. A benchmark I wrote suggests it can be *20 times slower* than an alternative. Please reproduce this @csgillespie. I suggest `ifelse()` itself could be re-written to be more efficient, but don't ask me how:

```r
marks = runif(n = 10e6, min = 30, max = 99)
system.time({
  result1 = ifelse(marks >=40, "pass", "fail")
})
system.time({
  result2 = rep("pass", length(marks)) 
  result2[marks < 40] = "fail"
})
identical(result1, result2)
```

Heads up @adamryczkowski and @richierocks who has written about this (I found this after writing that code btw) here: http://stackoverflow.com/questions/8831221/looking-for-a-more-efficient-ifelse 

We should mention this.

**Comment by csgillespie** [comment]
I get the same results.

See http://r.789695.n4.nabble.com/ifelse-woes-can-we-agree-on-a-ifelse2-td4723584.html about a recent discussion on a more efficient `ifelse`

Also, the second example (for consistency) should be
```
system.time({
  result2 = rep("fail", length(marks)) 
  result2[marks >= 40] = "pass"
})
```

**Comment by Robinlovelace** [comment]
Good points well made. I've updated the PR accordingly.
