### ISSUE TITLE
I must be doing something wrong, but I followed your instructions exactly.

### ISSUE THREAD

**Issue by ldlpdx** [csgillespie/efficientR#151]
Hi,

I did as you said. R was already up-to-date, but I updated R Studio and all of my packages, including `devtools`. Then I ran this:

    devtools::install_github("csgillespie/efficientR")

And got this:

    Downloading GitHub repo csgillespie/efficientR@master
    from URL https://api.github.com/repos/csgillespie/efficientR/zipball/master
    Error: Could not find build tools necessary to build efficientR

Is there a package necessary that you didn't mention in the instructions? I'm running on a Mac 64-bit with El Capitan 10.11.6.

**Comment by Robinlovelace** [comment]
One possibility is that you don't have gcc looking at this: http://stackoverflow.com/questions/37776377/error-when-installing-an-r-package-from-github-could-not-find-build-tools-neces

**Comment by csgillespie** [comment]
Would you try install another package, perhaps data.table or ggplot2?

We build the book using travis, so the command must(?) work. I think @Robinlovelace is correct, you are likely missing a compiler.

**Comment by ldlpdx** [comment]
Thanks @Robinlovelace and @csgillespie. Installing the compiler through Xcode for Mac worked.
