### ISSUE TITLE
Section 2.2.1 Exercise 2 is misleading

### ISSUE THREAD

**Issue by BillVenables** [csgillespie/efficientR#163]
The comment suggests the code will apply the median function to every column of the matrix X.  This is not what happens.  The code applies the median function to every element of the matrix X, resulting in 1e6 trivial calls to median().  Suggest you make X a data frame with 1e5 columns, not rows.

**Comment by csgillespie** [comment]
Thanks for this  it's **very** much appreciated.. I believe @Robinlovelace is revising that example today and this should be corrected then.
