### ISSUE TITLE
make pdf: underscore in caption

### ISSUE THREAD

**Issue by bowerth** [csgillespie/efficientR#214]
hello -
the underscore in `benchmark_std()` causes trouble for the pdf compilation. A single backslash, i.e. `benchmark\_std()` is not accepted, a double-backslash, i.e. `benchmark\\_std()` more or less works in the pdf but adds a backslash in the "make html" output.

``{r blas-bench, fig.width=6, fig.height=4, echo=FALSE, out.width="70%", fig.align="center", fig.cap="Performance gains obtained changing the underlying BLAS library (tests from benchmark_std())."}
local(source("code/02-blas.R", local=TRUE))
``

looking forward to your suggestions

**Comment by csgillespie** [comment]
I spent many hours with this same problem. Sadly my solution was to dump the pdf version.

**Comment by bowerth** [comment]
thanks for the quick reply - it seems, this is connected: https://github.com/yihui/knitr/issues/1334 https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#text-references -

the following compiles properly to PDF and HTML: 

```
(ref:foo) Performance gains obtained changing the underlying BLAS library (tests from `benchmark_std()`).

{r blas-bench, fig.width=6, fig.height=4, echo=FALSE, out.width="70%", fig.align="center", fig.cap="(ref:foo)"}
local(source("code/02-blas.R", local=TRUE))
```

**Comment by csgillespie** [comment]
Thanks. When we wrote the book, bookdown was still in development.
