### ISSUE TITLE
Suggestions on 3.7.1 compile function section

### ISSUE THREAD

**Issue by hxd1011** [csgillespie/efficientR#222]
It seems to me that R 3.4 comes with JIT compiler. And the demo (fig. 3.4) can not be replicated in current R.

![capture](https://user-images.githubusercontent.com/13385855/28480194-8b62bbfe-6e2d-11e7-95c4-3d81567f53d4.PNG)

**Comment by Robinlovelace** [comment]
Thanks for reporting this. More Colin's side of things than mine so look forward to see what he has to say on the matter.

**Comment by csgillespie** [comment]
@hxd1011 You're correct; 3.4.0 has the JIT compiler switched on by default (but not for additional packages). In the printed version of the book, we managed to sneak a footnote in the week before the was published (I monitor the R-Core commits).

I don't think I want to change the online version with a drastic change, e.g. removing the section. However, I'll add a note to say that this is for 3.3 and below.

Thanks
