### ISSUE TITLE
Error in sourceCpp [07-Performance.Rmd]

### ISSUE THREAD

**Issue by scottdk** [csgillespie/efficientR#223]
I am getting the following error when I try to knit 07-Performance.Rmd.

```
Warning message:
running command 'make -f "C:/PROGRA~1/R/R-34~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="sourceCpp_2.dll" WIN=64 TCLBIN=64 OBJECTS="file36a07eac128e.o"' had status 127 
Quitting from lines 999-1006 (_main.Rmd) 
Error in sourceCpp(code = code, env = env, rebuild = rebuild, cacheDir = cacheDir,  : 
  Error 1 occurred building shared library.
Calls: <Anonymous> ... withVisible -> eval -> eval -> cppFunction -> sourceCpp
```

I noted another thread here with a similar issue in **index.Rmd**, and followed your advice in that thread to knit each chapter individually. All were sucessful except 07-Performance.Rmd

Whether in **index.Rmd** or **07-Performance.Rmd**, the "Quitting from lines" are the following -

```
```{r tidy=FALSE}
library("Rcpp")
cppFunction('
  double add_cpp(double x, double y) {
    double value = x + y;
    return value;
  }
')
```

I have the latest Rtools version 3.4.0.1964
Latest R version 3.4.1 (2017-06-30)
Latest RStudio for Windows 1.0.153

On installing Rtools, I did select the option to edit the path and my path contains -
```
C:\WINDOWS\system32>path
PATH=C:\RBuildTools\3.4\bin;C:\RBuildTools\3.4\mingw_32\bin;
```

**Comment by csgillespie** [comment]
Would you trying running the problem code in an R terminal (no knitr)

**Comment by csgillespie** [comment]
Can't reproduce
