### ISSUE TITLE
[suggestion] Section 7.6.3 C++ data types

### ISSUE THREAD

**Issue by Jean-Romain** [csgillespie/efficientR#226]
You wrote section 7.6.3 that `int` can store values between -32768 and 32767. So a signed 16 bits value. It is a compiler choice if I well understood but an `int` is not 16 bits on my computer but 32 bits. I think it is what is commonly done nowadays 

I think it should be good to add a short paragraph about this question. How dangerous is for portability to consider an `int` being coded on 32 bits. Is it compiler dependent, OS dependent, architecture depended?

**Comment by Robinlovelace** [comment]
One for @csgillespie I think. Thanks for the question - will be interested to see the answer.

**Comment by csgillespie** [comment]
Thanks for the great comment. To be honest, this isn't something that I've thought about too much.

First thoughts are that you completely correct. However, the section on Rcpp is meant as a pointer to other resources. So I think a footnote might be more appropriate over an entire section.

Thanks again.
