### ISSUE TITLE
Two bugs in R code in chapter 6.

### ISSUE THREAD

**Issue by ConorIA** [csgillespie/efficientR#239]
Noticed a couple things as I read through Ch. 6 that didn't make sense. I've skimmed the chapter to remember what they were. I'm using the print copy of the book and the online version as reference. It seems two of my issues have already been corrected. I apologize if these others were already fixed in the code but not pushed to the online book. 

## Section 6.3 Exercises

It appears that the solution to the exercise appears in the book after the exercise, unless it is just meant to be a hint. If this is the solution, perhaps "expression" would be better than "function"?

> Write functions in stringr and base R that return:
> 
>    A logical vector reporting whether or not each string contains a number.
>    Complete words only, without extraneous non-letter characters.
> 
> 
> ```
> str_detect(string = strings, pattern = "[0-9]")
> #>  [1]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
> #> [12]  TRUE  TRUE
> str_extract(strings, pattern = "[A-z]+")
> #>  [1] NA       NA       "banana" NA       NA       "apple"  NA      
> #>  [8] NA       NA       NA       "Work"   NA       "Home"
> ```

## Section 6.4.2: 

> ```
> vapply(wb_ineq, class, character(1))
> #>     Country        code        Year   Year Code       top10       bot10 
> #> "character" "character"   "integer" "character"   "numeric"   "numeric" 
> #>        gini    b40_cons  gdp_percap 
> #>   "numeric"   "numeric"   "numeric"
> ```
> 
> This shows that although we loaded the data correctly all columns are seen by R as characters.

It seems that the column types have already been corrected.

**Comment by Robinlovelace** [comment]
- 6.3 Yes you're entirely currect it should be `expression` and the answer should be hidden.
- 6.4.2 Good point.

Would you be able to put in a Pull Request addressing each of these? I'll happily review it. Thanks again for pointing-out these issues.

**Comment by Robinlovelace** [comment]
Thanks for closing this.
