### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by csgillespie** [csgillespie/efficientR#25]

**Comment by richelbilderbeek** [comment]
What I am currently missing in Hadley's books:
 * Why to use stop() instead of returning NA (note: I also asked him to elaborate on this)
 * Guidelines in using the `tryCatch` functions efficiently

**Comment by csgillespie** [comment]
Thanks for the comments. Funnily enough I started a branch yesterday to address this issue (mainly your second point). The first point never occurred to me, but it would be a useful inclusion.

**Comment by csgillespie** [comment]
Added to https://csgillespie.github.io/efficientR/programming.html#communicating-with-the-user
