### ISSUE TITLE
Add working Dockerfile and Binder

### ISSUE THREAD

**Issue by Robinlovelace** [csgillespie/efficientR#259]
For reproducibility and learning.

**Comment by Robinlovelace** [comment]
Example of working Docker images supporting an open source book: https://github.com/geocompr/docker#geocomputation-with-r-in-docker

Example of a working Binder instance: https://mybinder.org/v2/gh/robinlovelace/geocompr/master?urlpath=rstudio

**Comment by Robinlovelace** [comment]
@csgillespie can you create a repo on hub.docker.com so that

```
docker run -it csgillespie/efficientr bash
```

Or similar will work on an auto-updated version?

**Comment by Robinlovelace** [comment]
Heads-up @csgillespie this fails:

```
docker pull csgillespie/efficientr
Using default tag: latest
Error response from daemon: manifest for csgillespie/efficientr:latest not found: manifest unknown: manifest unknown
```

Can you try manually getting the auto build to work form GH and the docker subfolders?

**Comment by Robinlovelace** [comment]
See here - no tagged releases: https://hub.docker.com/r/csgillespie/efficientr

**Comment by Robinlovelace** [comment]
Test binder here: https://mybinder.org/v2/gh/csgillespie/efficientR/master?urlpath=rstudio

**Comment by Robinlovelace** [comment]
Great news, the binder image works:

![image](https://user-images.githubusercontent.com/1825120/80913127-2bc26080-8d3a-11ea-8503-83b89dca45d6.png)

Final stage: copy the book's source code into the home directory.

**Comment by csgillespie** [comment]
@Robinlovelace This opens up a Jupyter notebook for me. Any ideas?

**Comment by csgillespie** [comment]
@Robinlovelace We now have three Dockerfiles:

- root directory (I copied for dockerhub)

**Comment by Robinlovelace** [comment]
We definitely need `.binder` so the Binder link works (try it) but don't need the docker one, happy for that folder to be deleted. Simplicity is good.
