### ISSUE TITLE
1.1 - Outdated MOSAIC pdf

### ISSUE THREAD

**Issue by engineerchange** [csgillespie/efficientR#263]
The MOSAIC pdf referenced in 01-introduction.Rmd is outdated (November 2015; R 3.2.2).

MOSAIC has an updated version (June 2018; R 3.5.0): https://github.com/ProjectMOSAIC/LittleBooks/tree/master/StudentGuide.

Published copies of the book have this as http://bit.ly/studentguider (linking to the former; may be worthwhile to update the bit.ly?)

**Comment by engineerchange** [comment]
The GitHub doesn't have a user-friendly / sustainable hyperlink to the PDF, so bit unclear if there is an easy resolution here.

**Comment by Robinlovelace** [comment]
Thanks for the heads-up. I've linked to the updated GitHub repo. If there other versions, or more appropriate and up-to-date and well-maintained resources altogether, a PR on this would be welcome!
