### ISSUE TITLE
2.3 - Ubuntu Wily reference is dead

### ISSUE THREAD

**Issue by engineerchange** [csgillespie/efficientR#267]
In a snippet in 2.3, Ubuntu 'Wily' is referenced and linked to, but CRAN doesn't have the binary for this version of Ubuntu listed anymore.

Snippet:
```
To download binary versions for Ubuntu ‘Wily’, for example, see cran.r-project.org/bin/linux/ubuntu/wily/
```

**Comment by csgillespie** [comment]
Thanks! I actually fixed this a few days but forgot to push :(

Now push
