### ISSUE TITLE
4.4.1: Issues replicating rdocumentation.org and RSiteSearch results

### ISSUE THREAD

**Issue by engineerchange** [csgillespie/efficientR#279]
Currently, Section 4.4.1 discusses two ways to search packages, both methods result in an issue for me.

The rdocumentation method notes the "multi-field search environment" that allows you to search by the Description field within the rdocumentation.org website. This "multi-field search" experience seems not to exist anymore; you get so many search results for packages when searching for 'haversine' now. Reporting the statistic that "18,433 package implement the Haversine formula" seems ill-advised since there's likely some other contextual search or recommendation engine built in now?

The RSiteSearch method has an error in reporting vignette results.

```
# Search CRAN for mentions of haversine
RSiteSearch("haversine")
```

results in

![rsitesearch](https://user-images.githubusercontent.com/3580210/82740711-555b2000-9d19-11ea-80a0-f34ef3187491.png)

Note the `vignettes: [ (can't open the index) ]` result.

Additionally, I tried the more detailed search and came up with a similar error.

```
RSiteSearch("haversine",restrict = "vignettes")
```

**Comment by Robinlovelace** [comment]
Thanks for reporting @engineerchange I'll take a look now.

**Comment by Robinlovelace** [comment]
I can reproduce the issue with `RSiteSearch()` and have sent an email to the email address at http://search.r-project.org/cgi-bin/namazu.cgi?query=Haversine&max=20&result=normal&sort=score&idxname=functions&idxname=vignettes&idxname=views


Dear Jonathan,

I've noticed that the RSiteSearch() function is not yielding results for Vignettes.

Please see here for details: https://github.com/csgillespie/efficientR/issues/279

Do you have any suggestions on how to overcome this, or where else to direct people to search?

Many thanks,

Robin

**Comment by Robinlovelace** [comment]
Heads-up @engineerchange and @csgillespie I've done some research and have updated the section accordingly in https://github.com/csgillespie/efficientR/pull/283. Seem good to you? I think that fixes this issue.

**Comment by Robinlovelace** [comment]
Reply from the developer:

> No. Sorry. I do have a list of sites (outdated) in
http://finzi.psych.upenn.edu. I don't know which ones might do this, if
any.

> I have maintained this site for 20 years. I have no time to fiddle with it
anymore. I can tell you how to replicate the whole thing, and then you can
try to fix it. The trick is to install the help files in html and as
little else as possible. Otherwise you would need an order of magnitude
more storage than I have.

> I think I decided many years ago that I didn't have room for vignettes for
what is now 16,000 packages. With so many packages, the search function is
essentially useless, but people keep using it anyway.

> I would love to just take it down, but apparently it is still the only site
that searches help files, albeit with an outdated (and probably risky)
search engine. If the computer dies, I will not replace it.
