### ISSUE TITLE
file.path

### ISSUE THREAD

**Issue by csgillespie** [csgillespie/efficientR#28]
In chapter 2, we go from using `file.path`

```{r, eval=FALSE}
site_path = R.home(component = "home")
fname = file.path(site_path, "etc", "Rprofile.site")
file.exists(fname)
```
to not using `file.path`
```{r, eval=FALSE}
if(!file.exists("~/.Rprofile")) # only create if not already there
  file.create("~/.Rprofile")    # (don't overwrite it)
file.edit("~/.Rprofile")
```

We should be consistent. @Robinlovelace Thoughts?

**Comment by Robinlovelace** [comment]
In my experience `file.path` is only useful in specific cases where there's a conflict between Windows and Unix-alike OS paths. In this case I suggest we don't use it - will remove I get the green light...

**Comment by csgillespie** [comment]
I'm happy with either. 

What about mentioning file path in an rmdnote

**Comment by Robinlovelace** [comment]
Sounds good - will do

**Comment by kevinushey** [comment]
FWIW, I think the main thing worth mentioning is that if you're calling an external program, depending on how that program behaves you might need Windows `\` slashes vs. `/` slashes (and so `normalizePath()` is your friend).

At the R level, using paths with `/` (or from `file.path()`) is generally the right thing to do; it's just munging those paths for e.g. calls to `system()` that can be tricky.

**Comment by csgillespie** [comment]
@kevinushey  Thanks, very helpful.

**Comment by richelbilderbeek** [comment]
One thing that IMHO is not covered in enough detail by Hadley's 'R Packages' is where to put raw files (pick from `/inst/exdata`, `/vignettes`, `/testthat/tests`), but also how to deal with finding these files. For example, when building a vignette, the folder `/vignette` is temporarily uses as a working directory, so a path like `/inst/exdata/my_file.txt` will fail there. 

As an ugly workaround I end up writing functions like this:

```
find_path <- function(filename) {
  if (file.exists(filename)) {
    return(filename)
  }

  prefixes <- c(
    "E:/Git/Cer2016/inst/extdata/",                                    # nolint
    "/home/richel/GitHubs/Cer2016/inst/extdata/",                      # nolint
    "/home/p230198/GitHubs/Cer2016/inst/extdata/",                     # nolint
    "/home/travis/build/richelbilderbeek/Cer2016/inst/extdata/",       # nolint
    "C:/Users/Aline/Cer2016/inst/extdata/"                             # nolint
  )
  for (prefix in prefixes) {
    full_path <- paste(prefix, filename, sep = "")
    if (file.exists(full_path)) {
      return(full_path)
    }
  }
  stop(
    "find_path: ",
    "cannot find '", filename, "'"
  )
}
```

I hope you guys come up with some clear guidelines on this. If you haven't already written something up one this :-)

**Comment by csgillespie** [comment]
Thanks. I've managed to somehow avoid this problem, so I don't much insight. Perhaps @Robinlovelace does.

I'm not sure if this fits naturally into the book, but we'll have a think.

**Comment by Robinlovelace** [comment]
Just been looking into this. Seems `inst/exdata` is the right place according to the first 3 results of an [internet search](https://www.google.pl/search?client=ubuntu&channel=fs&q=raw+data+site%3Acran&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=KWddV-TuKofD7gShvo_4Bg#channel=fs&q=raw+data+system.file+site:https:%2F%2Fcran.r-project.org%2F), the [R Packages](http://r-pkgs.had.co.nz/data.html) book (which says "If you want to store raw data, put it in inst/extdata") and this [question](http://stackoverflow.com/questions/26753518/package-a-large-data-set)

Here is a typical example, from the [**datapack**](https://cran.r-project.org/web/packages/datapack/vignettes/datapack-overview.html) package:

```r
csvfile <- system.file("extdata/sample-data.csv", package="datapack")
```

@kevinushey I'll add your insight and fix this asap.

Many thanks for the input.

**Comment by richelbilderbeek** [comment]
Awesome! Thanks for the research!
