### ISSUE TITLE
LinkingTo: Rcpp

### ISSUE THREAD

**Issue by spkal** [csgillespie/efficientR#35]
I think you need the line:
LinkingTo: Rcpp
in the DESCRIPTION file to avoid this error:
    `g++ -I/home/R/R-3.2.4/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c mean_c.cpp -o mean_c.o`
    `mean_c.cpp:1:18: fatal error: Rcpp.h: No such file or directory`
    `#include <Rcpp.h>`
when building the package

**Comment by csgillespie** [comment]
Thanks. I didn't spot the error.

The book isn't really a package. The DESCRIPTION file is just used to list dependencies.
