### ISSUE TITLE
Idea: mention size of each data type, and how integers take up half the space as numerics

### ISSUE THREAD

**Issue by daattali** [csgillespie/efficientR#39]
Most R programmers don't ever think about how much space data types take, and for small data sets it's not important. But since this is a book specifically about efficient R usage, maybe it's worth mentioning ie. if you have a 100MB matrix of numbers that are in numeric form but they're actually whole numbers, then casting them to int can save you 50MB

**Comment by csgillespie** [comment]
Done . I had included that information in an exercise, but your comment suggests that something that important should be more prominent.
