### ISSUE TITLE
"Under a proper OS, such as Linux,"

### ISSUE THREAD

**Issue by hrbrmstr** [csgillespie/efficientR#41]
found in "7.2 Cairo type". 

While I sympathize and echo the sentiment, prbly best to not directly alienate the 80% of Windows folks who are the main R users out there right in the book (which is why i leave the windows rants to twitter :-)

Totally grok this is a draft and this is a "placeholder/note" but it's also out for the world to see, now.

If you need me to test/validate anything on Macs (i also saw the mac comment), do not hesitate to ask.

**Comment by csgillespie** [comment]
Good point ;) 

Thanks.

**Comment by csgillespie** [comment]
@hrbrmstr I've started to look at the cairo question. Would you mind running a simple test [script](https://gist.github.com/csgillespie/43116e4ff3a560829a683705d940fa89) on a Mac and sending me the resulting png's?

My email is csgillespie@gmail.com

Thanks

**Comment by hrbrmstr** [comment]
![fig3](https://cloud.githubusercontent.com/assets/509878/16039699/58f6069c-31f9-11e6-8910-d667095cfca6.png)
![fig4](https://cloud.githubusercontent.com/assets/509878/16039700/58fa02f6-31f9-11e6-884f-fe0ca9935f3f.png)
![fig1](https://cloud.githubusercontent.com/assets/509878/16039698/58f18aea-31f9-11e6-8489-83e9c4a6d607.png)
![fig2](https://cloud.githubusercontent.com/assets/509878/16039697/58f1652e-31f9-11e6-9a70-88d7fcfd95e5.png)

**Comment by csgillespie** [comment]
Thanks

**Comment by csgillespie** [comment]
@hrbrmstr Interestingly the _italic text_ doesn't work under cairo; only an issue with Apple.

**Comment by hrbrmstr** [comment]
I'm >this< close to running a full on cross-platform R graphic device study. I have virtually no way to publish said work outside a blog post, but I think the state of graphics output in R is fairly abysmal, esp when it comes to fonts.

**Comment by csgillespie** [comment]
I presume you referring to https://github.com/hrbrmstr/r_device_tests ?

If you need help, please ping me.

In my experiments with `png` and standard fonts, I've found that the default driver under Windows could be improved by switching to `cairo` and Linux/Apple seem to have sensible defaults.

**Comment by Robinlovelace** [comment]
V. interesting. Seems no one other than you guys have done for a while...
