### ISSUE TITLE
Error building book on my system

### ISSUE THREAD

**Issue by smach** [csgillespie/efficientR#51]
I expect the problem is on my side if no one else is reporting it, but wonder if you might have any idea why I am receiving the following error when running `bookdown::render_book("index.Rmd",  bookdown::html_chapters())` after running `devtools::install_github("csgillespie/efficientR")`

    Quitting from lines 17-25 (_main.Rmd) 
    Error in eval(expr, envir, enclos) : object 'mychart' not found

**Comment by csgillespie** [comment]
I've just cloned the repo and ran 
```
bookdown::render_book("index.Rmd", bookdown::html_chapters())
```
and everything works. I also reran travis; everything seems to work there. Would you try `update.packages()`? Also, what version of R are you running?

**Comment by smach** [comment]
Recently installed the latest version, "Supposedly Educational." Tried updating packages, now I'm getting

    Quitting from lines 28-31 (_main.Rmd) 
    Error in xy.coords(x, y, xlabel, ylabel, log) : 
      'x' is a list, but does not have components 'x' and 'y'

I suspect something may be strange with my new library location, will investigate. On a Windows machine. Will try on a Mac and see what happens. Thank you.

**Comment by csgillespie** [comment]
@smach did you solve this problem?

**Comment by smach** [comment]
Thanks for asking! I'd given up, but since you were kind enough to check, I have installed the new version of R and tried again. That seems to have done the trick.

**Comment by csgillespie** [comment]
Great stuff. The book relies on a lot of packages. One of them must have had a R 3.3 dep'
