### ISSUE TITLE
Problem installing dependencies

### ISSUE THREAD

**Issue by marcusyoung** [csgillespie/efficientR#56]
Hi,

I'm trying to build the book. When I run:

devtools::install_github("csgillespie/efficientR")

I get the following error, after being prompted if I want to install additional tools:

Downloading GitHub repo csgillespie/efficientR@master
from URL https://api.github.com/repos/csgillespie/efficientR/zipball/master
Error: running command '"C:/R/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 1

Marcus

**Comment by csgillespie** [comment]
Sorry, not sure how this issue slipped past me.

Have you tried updating `devtools`? What version of R are you using?

**Comment by csgillespie** [comment]
I suspect the issue is lack of Rtools(??) but impossible to tell.
