### ISSUE TITLE
make pdf ...

### ISSUE THREAD

**Issue by nachti** [csgillespie/efficientR#65]
... throws an error using R 3.2.3:

###
...
label: voyages-pre (with options)
List of 3
 $ echo   : logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

Quitting from lines 2930-2941 (_main.Rmd)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: <Anonymous> ... withVisible -> eval -> eval -> read.delim -> read.table
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

Execution halted
make: *** [pdf] Error 1
###

I couldn't find _main.Rmd to check the respective lines

**Comment by Robinlovelace** [comment]
I'm not sure what set-up you have but the build seems to be passing on the automatic Travis test build, meaning this issue is not reproducible: https://travis-ci.org/csgillespie/efficientR/builds

If your wider issue is that you'd like a pdf of the latest version, this is provided the book's website: https://csgillespie.github.io/efficientR/

**Comment by csgillespie** [comment]
Does

```
library(efficient)
```
work?

**Comment by nachti** [comment]
@csgillespie No, it doesn't, but if it's renamed, it's no wonder, that #64 doesn't work.

**Comment by nachti** [comment]
`devtools::install_github("csgillespie/efficientR")` didn't install the efficient package while `devtools::install_github("csgillespie/efficient_pkg")` did it (dependency problem?)
Now it works to build a html document (unfortunately pdf is not possible at the moment due to *unknown graphics extension: .svg* ...)
Thanks for the hint @csgillespie

**Comment by csgillespie** [comment]
So I just deleted the `efficient`  package on my system and reran 

```
devtools::install_github("csgillespie/efficientR")
```
and it download everything that is needed. What version `devtools` are you using? I'm on version 1.11.1?

What version of R are you using?

Thanks for your feedback

**Comment by nachti** [comment]
```
R version 3.2.3 Patched (2016-01-01 r69832)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: openSUSE 13.1 (Bottle) (x86_64)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] devtools_1.7.0.9000
```

**Comment by csgillespie** [comment]
I think it might be a devtools issue; You're using an older version. I think `update.packages()` should solve that issue

**Comment by nachti** [comment]
Hmm - you are right. Using `devtools_1.11.1` solves the dependency problem.
Thank you very much Colin!
Now I just have to get rid of a LaTeX error (svg stuff) ...

**Comment by csgillespie** [comment]
Great. 

I've no idea about the `svg` issue; I don't think we have any svg's in the book. Could you provide more details?

**Comment by nachti** [comment]
I'm new to bookdown and just wanted to run it ;-)
```
LaTeX Warning: File `figures/800px-QWERTY-home-keys-position.svg' not found on
input line 505.


! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.505 ...ures/800px-QWERTY-home-keys-position.svg}
                                                   \caption{The starting pos...
```
The svg is included in 1.5 from wikipedia:
```latex
\begin{figure}
\includegraphics[width=11.11in]{figures/800px-QWERTY-home-keys-position.svg} \caption{The starting position for touch typing, with the fingers over the 'home keys'. Source: [Wikipedia](https://commons.wikimedia.org/wiki/File:QWERTY-home-keys-position.svg) under the Creative Commons license.}\label{fig:touch}
\end{figure}
```
Since I'm not root at the system, my possibilities are limited, but I'll check out the LaTeX installation.

**Comment by csgillespie** [comment]
This is an odd one. We have a file called `800px....position.svg.png` but we don't have any svg files. I think the problem is that the file is badly named - I'll blame @Robinlovelace  ;)  But googling suggests it's only an issue under certain OS's. 

I've renamed the file. Would you give that a try?

**Comment by Robinlovelace** [comment]
Caught red handed: https://github.com/csgillespie/efficientR/commit/c9482ab100fd85a0565b3b4b56543e2a5ca69ebd

**Comment by nachti** [comment]
Thanks it's working now. I added an option to the chunk to get it on a page. See #76 
*btw: maybe
+ data/co2.RData
+ data/co2.Rds
+ data/miniaa.Rds

should be included in `.gitignore`

**Comment by csgillespie** [comment]
Glad you got it working.

**Comment by nachti** [comment]
Thanks!
